[project]
name = "asteroids"
version = "0.1.0"
description = "Asteroids game"
requires-python = ">=3.8"
dependencies = [
    "pygame==2.6.1",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
